### ISSUE TITLE
Does not seem to detect pictures: 0 pictures found in 0 scan files

### ISSUE THREAD

**Issue by novmikvis** [Claytorpedo/scan-cropper#1]
Thank you for sharing the script! 
However I am having troubles using it. Any suggestions would be appreciated

Scanned black-and-white photos are stored in ./input folder
running
```
python scan_cropper.py -d ./input -n 0 -s 0.9 -t 230 -i 4 -b 9
```
returns:
```
0 pictures found in 0 scan files.
Program completed with 0 errors and warnings.
```
photo sample:
![](https://i.imgur.com/0EmhuYwl.png)

windows 10 
Python  3.7.2 x32
OpenCV 4.0.1 x32

**Comment by Claytorpedo** [comment]
Hello @miklide, sorry for getting back late -- only saw this now. When I wrote this project, it was using opencv 3, and it seems version 4 changed some things.

I've updated the program to correct this. Thank you for bringing it to my attention.


----
By the way, you will often have to tinker with the input values to find the right settings for your photoset. For instance, I tried `$ py scan_cropper.py -s 0.4 -t 200 -i 4` for what looks like reasonable results with your sample image. The biggest impact here is the large size difference between the three small photos and the one larger photo, which is why `-s 0.4` is used.

It seems like you may already be doing so here, but if you have a lot of photos to process, I recommend tuning the values to a small set of photos first. :)
